### ISSUE TITLE
The project cannot be built

### ISSUE THREAD

**Issue by fpavageau** [fbiville/neo4j-sproc-compiler#18]
Running `mvn clean package` works fine, but `mvn clean install` fails because it cannot find GPG:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project neo4j-sproc-compiler-parent: Unable to execute gpg command: Error while executing process. Cannot run program "gpg": error=2, No such file or directory -> [Help 1]

Should this be a mandatory step? Can't it be limited to releases?

**Comment by fbiville** [comment]
Yep, it should be limited to releases. Thanks for the bug report!
